const inscricaoSucesso = "<img src=\"http:\/\/54.233.121.72\/assets\/img\/banner-home.jpg\" width=\"1000px\" height=\"200px\" \/>\r\n<h4 style=\"text-align: center;\"><span style=\"color: #6E222E;\"><strong>Bem-Vindo<\/strong><\/span><\/h4>\r\n<p>&nbsp;<\/p>\r\n<p><span style=\"color: #000000;\"><strong>Sua inscri&ccedil;&atilde;o foi realizada com sucesso!<br \/>Acompanhe a gente\r\n      em nossas redes sociais para ficar por dentro de todas as novidades do Programa de P\u00F3s-Gradua\u00E7\u00E3o.<\/strong><\/span><\/p>\r\n<p>&nbsp;<\/p>\r\n<p><span style=\"color: #000000;\"><strong><a title=\"Facebook\" href=\"https:\/\/www.facebook.com\/FEUFRJ\/\" target=\"_blank\"\r\n        rel=\"noopener\">Facebook<\/a> | <a title=\"Instagram\" href=\"https:\/\/www.instagram.com\/ppgefeufrj\/\"\r\n        target=\"_blank\" rel=\"noopener\">Instagram<\/a><\/strong><\/span><\/p>\r\n<p>&nbsp;<\/p>\r\n<p>&nbsp;<\/p>";
const inscricaoProcessoSeletivo = "<img src=\"http:\/\/54.233.121.72\/assets\/img\/banner-home.jpg\" width=\"1000px\" height=\"200px\" \/>\r\n<h4 style=\"text-align: center;\"><span style=\"color: #6E222E;\"><strong>Sucesso<\/strong><\/span><\/h4>\r\n<p>&nbsp;<\/p>\r\n<p><span style=\"color: #000000;\"><strong>A inscri&ccedil;&atilde;o no Processo Seletivo foi realizada com sucesso!<br \/>Acompanhe a gente\r\n      em nossas redes sociais para ficar por dentro de todas as novidades do Programa de P\u00F3s-Gradua\u00E7\u00E3o.<\/strong><\/span><\/p>\r\n<p>&nbsp;<\/p>\r\n<p><span style=\"color: #000000;\"><strong><a title=\"Facebook\" href=\"https:\/\/www.facebook.com\/FEUFRJ\/\" target=\"_blank\"\r\n        rel=\"noopener\">Facebook<\/a> | <a title=\"Instagram\" href=\"https:\/\/www.instagram.com\/ppgefeufrj\/\"\r\n        target=\"_blank\" rel=\"noopener\">Instagram<\/a><\/strong><\/span><\/p>\r\n<p>&nbsp;<\/p>\r\n<p>&nbsp;<\/p>";
const atualizacaoParecerProcessoSeletivo = "<img src=\"http:\/\/54.233.121.72\/assets\/img\/banner-home.jpg\" width=\"1000px\" height=\"200px\" \/>\r\n<h4 style=\"text-align: center;\"><span style=\"color: #6E222E;\"><strong>Processo Seletivo<\/strong><\/span><\/h4>\r\n<p>&nbsp;<\/p>\r\n<p><span style=\"color: #000000;\"><strong>A sua inscri&ccedil;&atilde;o no Processo Seletivo foi atualizada. Acesse http://54.233.121.72 e confira. <br \/>Acompanhe a gente\r\n      em nossas redes sociais para ficar por dentro de todas as novidades do Programa de P\u00F3s-Gradua\u00E7\u00E3o.<\/strong><\/span><\/p>\r\n<p>&nbsp;<\/p>\r\n<p><span style=\"color: #000000;\"><strong><a title=\"Facebook\" href=\"https:\/\/www.facebook.com\/FEUFRJ\/\" target=\"_blank\"\r\n        rel=\"noopener\">Facebook<\/a> | <a title=\"Instagram\" href=\"https:\/\/www.instagram.com\/ppgefeufrj\/\"\r\n        target=\"_blank\" rel=\"noopener\">Instagram<\/a><\/strong><\/span><\/p>\r\n<p>&nbsp;<\/p>\r\n<p>&nbsp;<\/p>";
const vinculoPareceristaProcessoSeletivo = "<img src=\"http:\/\/54.233.121.72\/assets\/img\/banner-home.jpg\" width=\"1000px\" height=\"200px\" \/>\r\n<h4 style=\"text-align: center;\"><span style=\"color: #6E222E;\"><strong>Sucesso<\/strong><\/span><\/h4>\r\n<p>&nbsp;<\/p>\r\n<p><span style=\"color: #000000;\"><strong>Você foi selecionado como um parecerista para o Processo Seletivo do PPGE. Acesse a plataforma em: http://54.233.121.72 <br \/>Acompanhe a gente\r\n      em nossas redes sociais para ficar por dentro de todas as novidades do Programa de P\u00F3s-Gradua\u00E7\u00E3o.<\/strong><\/span><\/p>\r\n<p>&nbsp;<\/p>\r\n<p><span style=\"color: #000000;\"><strong><a title=\"Facebook\" href=\"https:\/\/www.facebook.com\/FEUFRJ\/\" target=\"_blank\"\r\n        rel=\"noopener\">Facebook<\/a> | <a title=\"Instagram\" href=\"https:\/\/www.instagram.com\/ppgefeufrj\/\"\r\n        target=\"_blank\" rel=\"noopener\">Instagram<\/a><\/strong><\/span><\/p>\r\n<p>&nbsp;<\/p>\r\n<p>&nbsp;<\/p>";
const esqueciSenha = "<img src=\"http:\/\/54.233.121.72\/assets\/img\/banner-home.jpg\" width=\"1000px\" height=\"200px\" \/>\r\n<h1><strong>UFRJ PPGE<\/strong>&nbsp;<\/h1><p>Para recuperar sua senha siga os passos abaixo:<\/p><p>1 - Acesse o seguinte endere\u00E7o <a href=\"http:\/\/54.233.121.72\/reset-senha\">ALTERAR SENHA<\/a><\/p><p>2 - Insira o seguinte c\u00F3digo no campo \"C\u00F3digo do email\": #senha#<\/p><p>3 - Insira sua nova senha no sistema e clique em Enviar<\/p>";

module.exports = {
    inscricaoSucesso,
    esqueciSenha,
    inscricaoProcessoSeletivo,
    vinculoPareceristaProcessoSeletivo,
};